version: 0.2

phases:
  pre_build:
    commands:
      - AWS_REGION=ap-south-1
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query account --output text)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/lms-app
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - docker build -t lms-app .
      - docker tag lms-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - echo "IMAGE PUSHED SUCCESSFULLY"
